# Copyright 2017-2018 Peter Williams <peter@newton.cx> and collaborators
# Licensed under the MIT License.

[workspace]
members = ["core", "visdata", "fits", "miriad", "casatables_impl", "casatables", "cli"]
