# Copyright 2017 Peter Williams <peter@newton.cx> and collaborators
# Licensed under the MIT License.

[package]
name = "rubbl_miriad"
version = "0.1.0"
authors = ["Peter Williams <peter@newton.cx>"]
license = "MIT"

[dependencies]
byteorder = "^1.1"
clap = "^2.26"
openat = "^0.1"
rubbl_core = { path = "../core", version = "0.1.0" }
