# Copyright 2017 Peter Williams <peter@newton.cx> and collaborators
# Licensed under the MIT License.

[package]
name = "rubbl_core"
version = "0.1.0"
authors = ["Peter Williams <peter@newton.cx>"]
license = "MIT"
homepage = "https://github.com/pkgw/rubbl"
repository = "https://github.com/pkgw/rubbl"
description = """
Core types and traits for Rubbl, a Rust package for astrophysics.
"""

[dependencies]
byteorder = "^1.1"
clap = "^2.26"
failure = "^0.1"
failure_derive = "^0.1"
ndarray = "^0.10"
num-complex = "^0.1"
termcolor = "^1.0"
