# Copyright 2017 Peter Williams <peter@newton.cx> and collaborators
# Licensed under the MIT License.

[package]
name = "rubbl_casatables"
version = "0.1.0"
authors = ["Peter Williams <peter@newton.cx>"]

[dependencies]
byteorder = "^1.1"
clap = "^2.26"
error-chain = "^0.11"
itertools = "^0.7"
ndarray = "^0.10"
nom = "^3.2"
num-traits = "^0.1"
pbr = "^1.0"
rubbl_casatables_impl = { version = "0.1.0", path = "../casatables_impl" }
rubbl_core = { version = "0.1.0", path = "../core" }

[build-dependencies]
gcc = { version = "^0.3", features = ["parallel"] }
